terrestris/shogun-admin

webpack.dev.config.js
Adds proxy for `client-config.js` served by shogun-boot backend while running in webpack dev mode.
This way, there is no need any more to adapt `fallbackConfig.js` in dev mode if the "real" config exists.
=> Proxy entry for client-config.js endpoint in webpack dev mode

assets/fallbackConfig.js, src/App.tsx, src/Component/Application/ApplicationEditForm/ApplicationEditForm.tsx, src/Component/Application/ApplicationRoot/ApplicationRoot.tsx, src/Component/Application/ApplicationTable/ApplicationTable.tsx, src/Component/Header/Header.tsx, src/Component/ImageFile/ImageFileEditForm/ImageFileEditForm.tsx, src/Component/ImageFile/ImageFileRoot/ImageFileRoot.tsx, src/Component/ImageFile/ImageFileTable/ImageFileTable.tsx, src/Component/Layer/LayerRoot/LayerRoot.tsx, src/Component/Layer/LayerTable/LayerTable.tsx, src/Component/Menu/Navigation/Navigation.tsx, src/Component/User/UserRoot/UserRoot.tsx, src/Component/User/UserTable/UserTable.tsx, src/Component/WelcomeDashboard/WelcomeDashboard.tsx, src/Page/Portal/Portal.tsx
This suggests to introduce a new config named `appPrefix` to override the app base path the admin is served on. This is needed for all routing handlers as soon as the admin is served under a non-root path, e.g. `https://localhost/myadmin`.
=> Configurable application root path

assets/fallbackConfig.js, src/Component/Menu/Navigation/Navigation.tsx, src/Component/Metrics/JdbcConnectionsActive/JdbcConnectionsActive.tsx, src/Component/Metrics/JvmMemoryUsed/JvmMemoryUsed.tsx, src/Component/Metrics/JvmThreadsLive/JvmThreadsLive.tsx, src/Component/Metrics/MetricEntry/MetricEntry.tsx, src/Component/Metrics/MetricsRoot/MetricsRoot.less, src/Component/Metrics/MetricsRoot/MetricsRoot.tsx, src/Component/Metrics/ProcessCpuUsage/ProcessCpuUsage.tsx, src/Component/Metrics/ProcessStartTime/ProcessStartTime.tsx, src/Component/Metrics/ProcessUptime/ProcessUptime.tsx, src/Component/Metrics/SystemCpuCount/SystemCpuCount.tsx, src/Component/Metrics/SystemCpuUsage/SystemCpuUsage.tsx, src/Component/Metrics/SystemLoadAverage/SystemLoadAverage.tsx, src/Page/Portal/Portal.tsx, src/Service/MetricService/MetricService.ts
This adds a new page `Metrics` containing assorted metrics made available from the `/actuator` endpoint.
=> Add menu entry showing assorted server metrics

webpack.dev.config.js
Removes hardcoded credentials and client ID for keycloak, uses placeholders instead.
=> Remove hardcoded keycloak credentials

src/Service/ApplicationService/ApplicationService.ts, webpack.dev.config.js
Make Keycloak realm configurable in dev setup in order to enable usage of admin with other realms than `SpringBootKeycloak` of shogun-boot.
=> Feature: make Keycloak realm configurable

webpack.common.config.js, webpack.dev.config.js
`.env` file is only required in development mode. Herewith, this is only loaded in `webpack.dev.config.js`
=> config: use dotenv only in dev mode

assets/formconfigs/application.json, src/Component/FormField/DisplayField/DisplayField.tsx, src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.less, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx, src/Component/Table/EntityTable/EntityTable.tsx, src/Controller/GenericEntityController.ts, src/Page/Portal/Portal.tsx, src/Util/TableUtil.tsx
This PR introduces an initial version of a generic, configurable (via model JSON files introduced in #51) entity table.
The configuration can be made using (optional) `tableConfig` property in model json
```
"tableConfig": {
"columnDefinition": [{
"title": "ID",
"dataIndex": "id",
"sortConfig": {
"isSortable": true,
"defaultSortOrder": "descend"
}
}, {
"title": "Name",
"dataIndex": "name",
"key": "name",
"sortConfig": {
"isSortable": false
},
"filterConfig": {
"isFilterable": true
}
}, {
"title": "Last modified",
"dataIndex": "modified",
"key": "modified",
"sortConfig": {
"isSortable": true
},
"cellRenderComponentName": "DateCell"
},{
"title": "Client configuration",
"dataIndex": "clientConfig",
"key": "clientConfig",
"cellRenderComponentName": "JSONCell"
}
]
}
```
For each …
=> Breaking: Introduce configurable entity table (initial version)

assets/fallbackConfig.js, package.json, src/Page/Portal/Portal.tsx, src/Service/CacheService/CacheService.ts, src/Service/GenericService/GenericService.ts, src/Service/GraphQLService/GraphQLService.ts, src/Service/LogService/LogService.ts, src/Util/SecurityUtil.ts
This adds a configuration object to configure the security authentication via json web token:
```js
security: {
jwt: true,
authTokenKey: 'shogun-auth-token'
}
```
The newly introduced `SecurityUtil` will take care of setting the needed headers:
1. The CSRF Token as before: Header `X-XSRF-TOKEN`
2. The JWT if configured in the admin-client-config as shown in the snippet: Header `AUTHORIZATION`
The AUTHORIZATION header will be collected via localStorage.getItem(config?.security?.authTokenKey)
As this is configurable this should not affect any running system.
=> Introduces configurable JWT authentication

README.md, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Component/Menu/User/User.tsx, src/Component/Modal/UserProfile/UserProfileForm/UserProfileForm.tsx, src/Component/User/UserTable/UserTable.tsx, src/Controller/GenericEntityController.ts, src/Model/User.ts, src/State/atoms.ts, src/Util/TableUtil.tsx, src/Util/UserUtil.ts
This removes all the keycloak stuff from the shogun-admin. Unfortunatley this includes the user details as these are unkonwn to the admin now.
In the future we should add config on how to get the username and so on from the `providerDetails` to the shogun `admin-client-config.js`.
=> Remove KeycloakRepresentation

src/Component/FormField/MarkdownEditor/MarkdownEditor.tsx
Title says it all.
Prevents the undesired behaviour when the cursor will jump to the end of the line on every change. This makes it impossible to edit text that is not at the end of the input.
=> fix: properly set markdown value on edit

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx, src/Component/Menu/Navigation/Navigation.tsx
This adds the `dataMapping` to the `tableConfig`.
This way values can be transformed befored displayed in the table.
e.g:
```json
"tableConfig": {
"dataMapping": {
"category":  {
"NEWS": "Neuigkeiten",
"MISC": "Redaktioneller Beitrag",
"TERMS": "Nutzungsbedingungen",
"CONTACT": "Kontakt",
"PRIVACYPOLICY": "Datenschutz",
"IMPRINT": "Impressum",
"LINK_ONLY": "Externer Link"
}
},
…
}
```
This also fixes some bugs:
- Clear entity form when hitting the create new entity button
- Make use of the navigationTitle in the navigation
It also moves the create button from the top right to above the table.
=> Introduces data mapping for table columns

src/App.less, src/Component/FormField/JSONEditor/JSONEditor.less, src/Component/FormField/JSONEditor/JSONEditor.tsx, src/Component/FormField/MarkdownEditor/MarkdownEditor.less, src/Component/FormField/MarkdownEditor/MarkdownEditor.tsx, src/Component/FullscreenWrapper/FullscreenWrapper.less, src/Component/FullscreenWrapper/FullscreenWrapper.tsx
Add `FullscreenWrapper` component which expands its underlying children to 100% viewport height and width.
Currently used with `JsonEditor` and `MarkdownEditor` components.
=> Introduce fullscreen wrapper

src/Component/FormField/JSONEditor/JSONEditor.less, src/Component/FormField/MarkdownEditor/MarkdownEditor.less, src/Component/FullscreenWrapper/FullscreenWrapper.less
* Ensure that wrapper takes a 100% height of viewport if fullscreen mode was activated
* Make wrapper resizable
This behaviour was broken with changes introduced via https://github.com/terrestris/shogun-admin/pull/80.
Please review @KaiVolland
=> Fix fullscreen mode

.dockerignore
This removes `nginx` and `dist` from `.gitignore` as they are need for the release.
~~It also moves the "Semantic Release" step to the end of the CI script so the tag is only created when pushing to the NEXUS-Repository finished correctly.~~ <-- This was undone in the rebase (force-push)
=> Fixes release via CI

src/Component/FormField/JSONEditor/JSONEditor.tsx, src/Component/FullscreenWrapper/FullscreenWrapper.less
This uses relative refs in the generated JSONSchema.
It also removes the `max-height` from the `FullscreenWrapper`.
=> JSONSchema generation and minor styling change

assets/fallbackConfig.js, src/Component/Header/Header.tsx
This removes the `config.path.base` prefix from the logo path in the Header.
:exclamation: It is a breaking change as existing configs may relied on the `path.base` configuration.
As this was the only usage of the base path in the admin client this can be removed completly from any `admin-client-config.js`.
=> Removes `config.path.base` from Logo in Header

src/Component/Menu/User/User.tsx
This will change the default label of the usermenu.
If a username is provided in the `providerDetails` it will be used. Otherwise the `authProviderId` will be used.
=> Use username if exists, providerId otherwise

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
Shows a simple error / success message when saving entities:
I chose to implement this in `GeneralEntityRoot` instead of the controller because this keeps anything UI related out of the controller. Let me know what you think.
=> feat: add feedback when saving entities

.releaserc.json
Follow-up to #108 
With this plugin semantic-release should create a github release again.
=> fix: add semantic-release github plugin

assets/formconfigs/application.json, assets/formconfigs/user.json
config: adds missing translation
style: Abbreviations are replaced by the actual word
=> Json missing translations

.github/workflows/release.yaml, package.json
Sets up Node.js, scans the Jest coverage and sends the report to SonarQube.
=> ci: scans the jest coverage and sends a report to sonarqube

src/Component/FullscreenWrapper/FullscreenWrapper.less
Ensures fullscreen for all childs except the first. So the JSON-Editor will be opened in fullscreen
.
=> fix: ensures fullscreen for all childs except the first

assets/formconfigs/application.json, src/Component/FormField/LinkField/LinkField.tsx, src/Component/FullscreenWrapper/FullscreenWrapper.tsx, src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx, src/i18n/translations.ts
Adds missing translations.
A check is included, that asks for a title. If no title exists, a default i18n.key will be used.
=> fix: adds missing translation

src/Component/FormField/JSONEditor/JSONEditor.less, src/Component/FormField/MarkdownEditor/MarkdownEditor.less, src/Component/FormField/MarkdownEditor/MarkdownEditor.tsx, src/Component/FullscreenWrapper/FullscreenWrapper.less
Reverts https://github.com/terrestris/shogun-admin/pull/117 since it breaks the visibility of the child elements completely, if at least 2 lines in JSON editor are defined.
Partially reverts https://github.com/terrestris/shogun-admin/pull/96:
* Restore 100% height of the child elements in the fullscreen mode
* Restore style removing uneeded elements (separator) on markdown toolbar
=> Fix fullscreen mode again

assets/formconfigs/application.json, assets/formconfigs/layer.json, assets/formconfigs/user.json, src/Component/FormField/JSONEditor/JSONEditor.tsx, src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx, src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx
This fixes the generation of the JSON schemas for properties including an array of referenced schemas, e.g. the `toolConfig` of applications which enables the JSON validation for this fields.
Note: The fieldProp `entityName` is no longer needed as the type will be evaluated automatically based on the appropriate `dataField` now.
=> Fix JSON schemas for array types

.github/workflows/release.yaml
Switches to docker-public.terrestris.de so the image will be available publicly.
https://github.com/orgs/terrestris/teams/devs Please note.
=> use docker-public.terrestris.de registry

.github/workflows/release.yaml
Switches to docker-public.terrestris.de so the image will be available publicly.
This time with the correct branch.
=> feat: use docker-public.terrestris.de registry

assets/fallbackConfig.js, src/i18n/translations.ts, src/index.tsx
This suggests to introduce a check for authorized roles before showing the `<App>` component. 
Even if logged in, a user must not have the legitimate role to actually access the SHOGun interfaces and typically only users with the `admin` role are intended to open the admin UI.
Please note the update of the config file for implementing this feature!
=> Show app only if the current user has an appropriate role

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Controller/ControllerUtil.ts
This properly resets the `formIsDirty` and `editEntity` states to always reflect the correct form state, e.g. to (de-)activate the save button.
=> Properly reset the dirty state of the entity form

assets/fallbackConfig.js, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.less, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/i18n/translations.ts
This suggest to add a button to upload a local dataset (GeoTIFF or zipped shapfile) to the GeoServer and creating a new coverage/feature type based on it.
https://user-images.githubusercontent.com/9415123/200905043-9f2d60ab-637e-4c77-9510-a8e7e8df5ac4.mp4
=> Layer upload (GeoTIFF and zipped SHP)

src/Component/Menu/Navigation/Navigation.tsx
Get rid of antd warnings regarding deprecated menu component configuraion with `children` via switch to `items` property.
Non-functional change.
=> Update deprecated menu configuration

src/App.tsx, src/Component/FormField/JSONEditor/JSONEditor.tsx, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Page/Portal/Portal.tsx, src/State/atoms.ts, src/Util/OpenAPIUtil.ts, src/index.tsx, webpack.common.config.js
This adds a completion provider for the `JSONEditor` that resolves the value of all `layerId` fields in the editor with the actual layer name (and the full JSON config object as documentation).
=> Show suggestions for `layerId` fields in the JSON editor

.github/workflows/release.yaml
This fixes the failing `release` pipeline, see [here](https://github.com/cycjimmy/semantic-release-action/issues/143) for details.
=> Pin version of semantic release to compatible one

src/Controller/GenericEntityController.ts
Undefined Values can now be send to the Backend due to a change of the request method.
=> Send undefined values to the backend

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
The function `form.resetFields()` creates an empty object, the form value needs to be replaced with the initial value after clearing the input.
=> fix: resets the input form to the initial value

src/index.tsx
This fixes the reloading loop in some browsers (e.g. Firefox) by disabling checking the login status in an iframe.
See [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#session-status-iframe) for further details.
=> Fix infinite reload loop

src/Component/Layer/LayerTypeSelect/LayerTypeSelect.tsx
This suggests to get the actual layer types from the type defined in the `shogun-util` and to make list of supported ones configurable.
=> Simplify `LayerTypeSelect`

src/Util/OpenAPIUtil.ts
This adds support for the [discriminator](https://swagger.io/specification/) field in the SHOGun OpenAPI specification while generating the JSON schema, used in combination with [PR 710](https://github.com/terrestris/shogun/pull/710).
=> fix: determine discriminator values

src/Component/Logs/Logs.less, src/Component/Logs/Logs.tsx, src/Service/LogService/LogService.ts, src/i18n/translations.ts
This suggests to apply several minor fixes to the logs page:
- Fix disabling of the automatic log refresh.
- Adjust styling to show the full scrollbar and show a loading indicator.
- Replace the `TextArea` with a `pre` element.
- Add a note if the log can't be shown.
Preview:
=> Several fixes to the logs page

assets/formconfigs/group.json, assets/formconfigs/user.json, src/Component/FormField/VerifyProviderDetailsField/VerifyProviderDetailsField.less, src/Component/FormField/VerifyProviderDetailsField/VerifyProviderDetailsField.spec.tsx, src/Component/FormField/VerifyProviderDetailsField/VerifyProviderDetailsField.tsx, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx, src/i18n/translations.ts
This includes the cell renderer component `VerifyProviderDetailsField` that can be used to show a warning besides a `User` or `Group` table column cell to show a warning if the user/group is not available in the authentication provider (=Keycloak).
To enable it provide a model config (e.g. in the `user.json`) like:
```json
{
"title": "#i18n.titleKeyId",
"dataIndex": "authProviderId",
"key": "authProviderId",
"cellRenderComponentName": "VerifyProviderDetailsCell",
"cellRenderComponentProps": {
"title": "#i18n.userDoesNotExistTitle"
}
}
```
=> Init `VerifyProviderDetailsField` cell renderer

src/Component/LogSettings/LogLevelTable/LogLevelTable.tsx
When calling Logging-Level Table the data would not show until the search button was clicked. This was a fault in the condition. This push fixes this issue.
=> fix: fixed a bug where Logging-Level Table would not show its values

webpack.dev.js
This updates the webpack dev server configuration by:
- Removing an internal path.
- Readding the [historyApiFallback](https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback) option to make routing work again.
=> Update webpack dev server configuration

src/App.tsx, src/State/atoms.ts
This fixes the suggestions for layerIds by adjusting the range property. Newer versions of monaco-editor require the range to be set and to be a single line range.
The range was adjusted so that suggestions replace the characters of a typed word, if there are any. Otherwise suggestions will just be added to the current cursor position.
This also adjusts the default value of the suggestions, so that they will be fetched when refreshing the application view.
=> fix: fix setting range for layerId suggestions

Dockerfile.dev, README.md, webpack.common.js, webpack.dev.js
This updates the webpack development server configuration by:
- changing the protocol from `https` to `http` (in the [recommended setup](https://github.com/terrestris/shogun-docker) it's proxied by a https server anyway).
- fixing the websocket client path to match the location given in the [nginx](https://github.com/terrestris/shogun-docker/blob/main/shogun-nginx/dev/default.conf#L95) proxy.
- setting the http port to 8080 (not needed in particular to be honest).
Together with [PR 92](https://github.com/terrestris/shogun-docker/pull/92) this fixes the need to manually confirm the development certificate for the web socket connection.
=> Fix development server websocket configuration

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
When table filter is active, the pagination should be removed in entity fetch in order to get all results matching the filter.
=> fix: remove pagination from query when table is filtered

.github/workflows/release.yaml
Hopefully, this solves the SonarCube Trigger workflow  that currently fails when a release is performed.
=> fix: set sonarcube project base directory

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
This fixes a serious bug that ensures that an existing entity (app or layer) will not be overwritten/lost. The bug could be reproduced by
1. Open (generic) form of an entity
2. Click on "Create new ..." 
3. Set basic value like name
4. Click save
After that, the entity opened in step 1 is fully lost/overwritten.
=> fix: do not overwrite existing entity

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx
1) Filter and sorting as well are now individual for every entity by adding the key to the table. Beforehand the filter and sorting were active for every entity.
2) The pagination element is now loaded when changing the entity. Beforehand it disappeared when the reset button wasn't clicked.
@mholthausen
=> fix: sort and filter for every entity and pagination

Dockerfile, Dockerfile.dev
This PR updates the Dockerfiles to use the current Nodejs LTS version (`20.12.1`), `alpine3.19` and `nginx1.25.4`
@terrestris/core please review
=> Use node LTS (v20.12.1) and alpine 3.19

src/Component/ImageFile/ImageFileForm/ImageFileForm.less, src/Component/ImageFile/ImageFileForm/ImageFileForm.tsx, src/Component/ImageFile/ImageFileForm/ImageForm.spec.tsx, src/Component/ImageFile/ImageFileRoot/ImageFileRoot.less, src/Component/ImageFile/ImageFileRoot/ImageFileRoot.tsx, src/Component/ImageFile/ImageFileTable/ImageFileTable.tsx, src/i18n/translations.ts, test/setup.js
This introduces the `ImageFileForm`. It replaces the previously existing preview and adds some more information, aswell as the public switch. As the public state of an entity is handled via its id the routing was modified. See breaking change info below.
:exclamation: BREAKING CHANGE: The route to an specific ImageFile now needs the image-id instead of the image-uuid
=> Introduces `ImageFileForm`

src/Controller/GenericEntityController.ts
As `this.entity` gets overwriten in [Line 168](https://github.com/terrestris/shogun-admin/compare/fix-public?expand=1#diff-b1c96cc29cbab0fccd7ccf775e2b62022549afca1b509f3b479f51b98b69ef1dL168) we have to read the value before.
=> Fix saving of public state

src/App.less
This PR centers the logo while loading the shogun-admin as described in [#21849](https://redmine.intranet.terrestris.de/issues/21849?include=journals&journals=all)
Picture of the issue:
After fixing:
Please review :)
=> fix: center the logo while loading

.github/workflows/on-push-main.yml
This MR ensures that merging from dependabot does not send a report to sonarqube
=> Sonar-Scan

.github/workflows/release.yaml, .releaserc.json, package.json
This will update the release pipelines as follows:
- publishing to npm will be activated so that you can use the `shogun-admin` as a dependency
- when pushing to the branch `next` and automated prerelease will be triggered `x.x.x-next.x`
- automated releases for the main branch have been disabled and have to be triggered manually
=> Update release pipelines

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/i18n/translations.ts
This PR adds a new modal to warn the user that their changes were not saved in case they switch entity without saving there changes. The modal look like this:
=> feat: adds a save warning when entity is changed

.github/workflows/on-push-main.yml
This updates the SonarQube scan action to use the SonarSource/sonarqube-scan-action@v2.3.0
This is necessary, because the previous SonarQube scanner causes an error with SonarQube version 10.6.
=> ci: update sonarqube-scanner

src/Component/ImageFile/ImageFileForm/ImageFileForm.tsx
This is needed since the endpoint doesn't accept a string as input here.
=> Pass image ID as number to GraphQL endpoint

package-lock.json, package.json, src/Component/CreateAllGroupsButton/CreateAllGroupsButton.spec.tsx, src/Component/CreateAllGroupsButton/CreateAllGroupsButton.tsx, src/Component/CreateAllRolesButton/CreateAllRolesButton.spec.tsx, src/Component/CreateAllRolesButton/CreateAllRolesButton.tsx, src/Component/CreateAllUsersButton/CreateAllUsersButton.spec.tsx, src/Component/CreateAllUsersButton/CreateAllUsersButton.tsx, src/Component/FormField/Permission/InstancePermissionGrid/InstancePermissionGrid.spec.tsx, src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.spec.tsx, src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx, src/Component/GeneralEntity/Slots/ToolbarCreateAllGroupsButton/ToolbarCreateAllGroupsButton.tsx, src/Component/GeneralEntity/Slots/ToolbarCreateAllRolesButton/ToolbarCreateAllRolesButton.tsx, src/Component/GeneralEntity/Slots/ToolbarCreateAllUsersButton/ToolbarCreateAllUsersButton.tsx, src/Component/GeneralEntity/Slots/ToolbarUploadLayerButton/ToolbarUploadLayerButton.tsx, src/Component/ImageFile/ImageFileRoot/ImageFileRoot.spec.tsx, src/Component/Menu/Navigation/Navigation.spec.tsx, src/Component/Menu/Navigation/Navigation.tsx, src/Component/UploadLayerButton/UploadLayerButton.spec.tsx, src/Component/UploadLayerButton/UploadLayerButton.tsx, src/Context/GeneralEntityRootContext.tsx, src/Page/Portal/Portal.tsx, src/i18n/translations.ts, src/test-util.tsx
This adds a button to each of the `User`, `Group` and `Role` panels to trigger the creation of the given entities from the respective provider (see [#947](https://github.com/terrestris/shogun/pull/947)). Generally it just adds all missing entities, e.g. all users that are present in the user provider (usually Keycloak), but not in SHOGun.
In addition this:
- Refactors the `GeneralEntityRoot` for more flexible and generic support for entity specific components to render (currently only for the toolbar above the entity table, but this might be adjusted for future needs) by introducing a local context including some props that were shared between all sub components.
- Fixes a regression of missing support for additional navigation menu entries besides the default ones.
Requires …
=> Introduce buttons to create users, groups and roles from the respective provider

src/App.tsx, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Hooks/useExecuteWfsDescribeFeatureType.ts, src/State/atoms.ts
This PR introduces a list with suggestions for propertyName in the editFormConfig or featureInfoFormConfig in the layer config in shogun-admin. The suggestions are determined via a WFS-DescribeFeatureType query.
Please note: the suggestion list can only be provided, when the layer is already saved!
=> fix: introduce suggestions for property name

src/App.tsx, src/Component/FormField/Permission/GroupPermissionGrid/GroupPermissionGrid.tsx, src/Component/FormField/Permission/InstancePermissionGrid/InstancePermissionGrid.tsx, src/Component/FormField/Permission/PermissionModal/PermissionModal.spec.tsx, src/Component/FormField/Permission/PermissionModal/PermissionModal.tsx, src/Component/FormField/Permission/RolePermissionGrid/RolePermissionGrid.tsx, src/Component/FormField/Permission/UserPermissionGrid/UserPermissionGrid.tsx, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
Currently loading the list of entities and an entity itself (e.g. the list of applications and selection an application from the list) results in a lot of duplicated or unwanted requests to the backend fetching the payload multiple times or too early.
This fixes several of the observed loading behaviours by:
- applying the default sorter as default state value to reduce the initial loading of the entity lists to a singel request.
- caching the `modalProps` in the instance permission grids to prevent unwanted rerenders (the previous approach was creating new object reference on each render). 
- load the users/groups/roles in the permission grids as lazy as possible (by opening the select dropdown only).
In addition it removes the custom `tagRenderer` from the role permission grid - …
=> Optimize (remote) loading behaviours

src/Component/FormField/Permission/UserPermissionGrid/UserPermissionGrid.less, src/Component/FormField/Permission/UserPermissionGrid/UserPermissionGrid.tsx, src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx, src/i18n/translations.ts
This updates the style of the permissions grids:
1. Show a note if the grids can't be shown in create mode.
- Before:
- After:
2. Update the custom tag style for users to the default ones in the select input field:
- Before:
- After:
- Compared to the default tags:
=> Minor style adjustments to the permission grids

.github/workflows/nodejs.yml, jest.config.js, sonar-project.properties
This merge requests adds an automatic comment for each pull request, showing the test coverage reported by jest. Test results are reported for the entire code, as well as for changed files. If no tests were found related to the files changed, this is also reported.
=> ci: add coverage comment on pull request

rspack.common.js, src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx, src/Controller/ControllerUtil.ts, src/Controller/GenericEntityController.ts
This fixes an annoying bug while creating a new entity (e.g. an application configuration) in environments where a `defaultEntity` is set. In such scenarios any user input to the configuration template will be overwritten on save.
In addition it fixes an error in the rspack configuration.
=> Fix entity templates

.github/workflows/release.yaml, .github/workflows/release_docker.yml, .github/workflows/update_base_images.yaml, Dockerfile, Dockerfile.dev
This introduces regulary (cronjob based) updates of the base images:
* add `RUN apk update && apk upgrade --no-cache` after all base images
* extract a new "release docker" workflow that can be called by other workflows
* as before: for releases (also next branch)
* in future: use by another new workflow "update base images" that will regulary update the base images
=> feat: introduce regulary updated docker images

.github/workflows/nodejs.yml
This fixes the automatic comment reporting the test-coverage for each pull request to avoid getting "null"-comments like this:
=> ci: fix coverage comment

src/Component/Logs/Logs.tsx, src/Service/LogService/LogService.ts
This fixes a minor issue of an uncatched error in the `Logs` component if the logfile can't be fetched (e.g. in the development setup) by not rethrowing/rejecting in the service's catch clause.
=> Don't throw error in catch

.github/workflows/update_base_images.yaml
Uses a github workflow matrix strategy to dynamically run a "update docker base image" workflow based on a dynamic list of latest git tags.
A `git tag` command is used to filter by the following rules:
* Minimum version: Only tags with a major version >= v17 are included (where the docker base image feature has been introduced)
* Only one "-next" version: Displays only the latest -next.x tag, if present.
* Limit Per Major Line: Shows up to 3 tags per major version.
* The final output is limited to 10 tags.
=> ci: use matrix strategy with dynamic git tag list
