package.json
src/App.tsx
src/Component/Header/Header.tsx
src/Component/Menu/User/User.tsx
src/Component/Modal/UserProfile/UserProfile.tsx
src/Component/Modal/UserProfile/UserProfileForm/UserProfileForm.tsx
src/State/atoms.ts

This introduces recoikl.js as state managment library.

Introduces recoil.js as state manager

---

assets/fallbackConfig.js
src/Component/Application/ApplicationRoot.tsx
src/Component/Application/ApplicationTable/ApplicationTable.less
src/Component/Application/ApplicationTable/ApplicationTable.tsx
src/Component/Table/EditableCell.tsx
src/Model/Application.ts
src/Page/Portal/Portal.tsx
src/Service/ApplicationService/ApplicationService.ts
src/Util/TableUtil.tsx
webpack.dev.config.js

This introduces the `ApplicationTable` and corresponding components.
Aferwards we gonna try if we can make this generic to cover all entities.

Introduces the ApplicationTable

---

webpack.dev.config.js

Remove proxy header location manipulation for dev setup

---

assets/fallbackConfig.js
src/Component/Application/ApplicationTable/ApplicationTable.tsx
src/Component/Header/Header.tsx
src/Component/WelcomeDashboard/WelcomeDashboard.less
src/Component/WelcomeDashboard/WelcomeDashboard.tsx
src/Page/Portal/Portal.tsx

This introduces the `WelcomeDashboard` and adds some small fixes.
The Dashboard currently contains some placeholders.
@annarieger please review

Welcome Dashboard

---

src/Component/Application/ApplicationTable/ApplicationTable.less
src/Component/Application/ApplicationTable/ApplicationTable.tsx

Highlights column by id from route

---

src/Component/Header/Header.less
src/Component/Header/Header.tsx
src/Component/Menu/Navigation/Navigation.tsx
src/Component/Menu/User/User.less
src/Component/Menu/User/User.tsx
src/Component/Modal/ApplicationInfo/ApplicationInfo.spec.tsx
src/Component/Modal/ApplicationInfo/ApplicationInfo.tsx
src/Component/Modal/UserProfile/UserProfile.tsx
src/Page/Portal/Portal.less
src/Page/Portal/Portal.tsx
src/State/atoms.ts
src/test-util.tsx

Header and Menu enhancements

---

src/Component/Application/ApplicationRoot/ApplicationRoot.less

Adds a vertical seperator line

---

package.json
src/Component/Application/ApplicationEditForm/ApplicationEditForm.less
src/Component/Application/ApplicationEditForm/ApplicationEditForm.tsx
src/Component/Application/ApplicationRoot/ApplicationRoot.tsx
src/Component/Application/ApplicationTable/ApplicationTable.tsx

Adds first state of `ApplicationEditForm`
Please review @KaiVolland

Create or Edit Application form

---

assets/fallbackConfig.js
src/Component/Header/Header.tsx
src/Component/Layer/LayerRoot/LayerRoot.less
src/Component/Layer/LayerRoot/LayerRoot.tsx
src/Component/Layer/LayerTable/LayerTable.tsx
src/Component/Table/EntityTable/EntityTable.less
src/Component/Table/EntityTable/EntityTable.tsx
src/Component/User/UserRoot/UserRoot.less
src/Component/User/UserRoot/UserRoot.tsx
src/Component/User/UserTable/UserTable.tsx
src/Component/WelcomeDashboard/WelcomeDashboard.tsx
src/Model/Enum/LayerType.ts
src/Model/Layer.ts
src/Page/Portal/Portal.tsx
src/Service/LayerSerivce/LayerService.ts
src/Util/TableUtil.tsx

This introduces the EntityTable.
It can be used as basecomponent to easily setup a table for every Entity.
It also adds the User and Layer related code and UI.

Introduces EntityTable

---

README.md
assets/index.html
package.json
src/Component/Application/ApplicationEditForm/ApplicationEditForm.less
src/Component/Application/ApplicationEditForm/ApplicationEditForm.tsx
src/Component/Application/ApplicationTable/ApplicationTable.tsx
src/Component/FormField/DisplayField/DisplayField.tsx
src/Component/FormField/JSONEditor/JSONEditor.less
src/Component/FormField/JSONEditor/JSONEditor.tsx
src/Component/Layer/LayerTable/LayerTable.tsx
src/Component/Table/EntityTable/EntityTable.less
src/Component/Table/EntityTable/EntityTable.tsx
src/Component/User/UserTable/UserTable.tsx
src/Component/WelcomeDashboard/WelcomeDashboard.tsx

This adds several enhancements:
- Updates the `README.md`
- Updates the config path where the shogun file is expected
- Refactors the `EntityTable` action config
- Replaces the custom `ApplicationTable` with the `EntityTable`
- Introduces the `DisplayField` and `JSONEditor` and uses them in the `ApplicationEditForm` (see below)
- Adds some minor styling improvements to the Form

Introduces several enhancements

---

README.md

Title says it all, please review.

Fix some typos, enhance wording

---

src/Service/GenericService/GenericService.ts

This introduces the `updatePartial` interface to the `GenericSerivce`.
It requires [SHOGun 6.1.0](https://github.com/terrestris/shogun/releases/tag/v6.1.0).
For details see https://github.com/terrestris/shogun/pull/172.

Adds updatePartial interface to GenericService

---

assets/fallbackConfig.js
package-lock.json
package.json
src/Component/ImageFile/ImageFileEditForm/ImageFileEditForm.less
src/Component/ImageFile/ImageFileEditForm/ImageFileEditForm.tsx
src/Component/ImageFile/ImageFileRoot/ImageFileRoot.less
src/Component/ImageFile/ImageFileRoot/ImageFileRoot.tsx
src/Component/ImageFile/ImageFileTable/ImageFileTable.less
src/Component/ImageFile/ImageFileTable/ImageFileTable.tsx
src/Component/Menu/Navigation/Navigation.tsx
src/Component/Table/EntityTable/EntityTable.tsx
src/Model/File.ts
src/Model/ImageFile.ts
src/Page/Portal/Portal.tsx
src/Service/ImageFileService/ImageFileService.ts

This introduces models, service and ui-components to list and preview ImageFiles.

ImageFile handling

---

package.json
webpack.dev.config.js

Log into the backend and use HTTPS for the webpack dev server.
@terrestris/devs Please review.

Add login and SSL

---

.gitignore

Ignore dist folder

---

package-lock.json
package.json
webpack.common.config.js
webpack.dev.config.js
webpack.production.config.js

Make use of [`simple-progress-webpack-plugin`](https://github.com/dominique-mueller/simple-progress-webpack-plugin) to enhance and significantly short the amount of produced output lines while npm build phase.

Use simple-progress-webpack-plugin

---

src/Component/Application/ApplicationRoot/ApplicationRoot.less
src/Component/EvictCache/EvictCache.tsx
src/Component/GlobalSettings/GlobalSettingsRoot/GlobalSettingsRoot.less
src/Component/GlobalSettings/GlobalSettingsRoot/GlobalSettingsRoot.tsx
src/Component/LogSettings/LogLevelTable/LogLevelTable.tsx
src/Component/Logs/Logs.tsx
src/Component/Menu/Navigation/Navigation.tsx
src/Page/Portal/Portal.tsx
src/Service/CacheService/CacheService.ts
webpack.dev.config.js

This suggests to add new panel `Global settings`. Currently there is a single button for clearing the hibernate cache of shogun only. More options might follow…

Add global settings panel

---

assets/fallbackConfig.js

This adds some missing entries in the fallback config.

Add missing entries for global settings page

---

src/Component/Application/ApplicationRoot/ApplicationRoot.less
src/Component/FormField/JSONEditor/JSONEditor.less
src/Component/Layer/LayerRoot/LayerRoot.less
src/Component/Logs/Logs.less
src/Component/User/UserRoot/UserRoot.less
src/Page/Portal/Portal.less

Enhances usability by keeping content in range instead of endless scrolling pages

Make most views have a fixed height and scrollable content

---

.github/workflows/nodejs.yml
assets/fallbackConfig.js
package-lock.json
package.json
src/Component/Application/ApplicationEditForm/ApplicationEditForm.tsx
src/Component/FormField/JSONEditor/JSONEditor.tsx
src/Component/Layer/LayerEditForm/LayerEditForm.tsx

This enables validation for the JSON fields of the SHOGun entities based on the OpenAPI specification. 

Enable JSON schema validation for JSON entity fields

---

.github/workflows/release.yaml

Update to jdk 17

---

.gitignore
README.md
assets/index.html
package.json
src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Page/Portal/Portal.tsx
webpack.common.config.js
webpack.dev.config.js
webpack.production.config.js

This modifies the webpack.dev.config.js to work properly with shogun-docker. See updated README.md for details.
It also adds the `Select` and `Markdown` (real markdown editor will be added in a followup) keys to the `GeneralEntityForm`.

Docker dev server

---

package-lock.json
package.json
src/Component/FormField/MarkdownEditor/MarkdownEditor.tsx
src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx

Make use of https://uiwjs.github.io/react-md-editor/ for more comfortable editing of markdown based fields.

Introduce markdown editor field

---

src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.less
src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.less
src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.less
src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx
src/Component/Table/EntityTable/EntityTable.tsx

* Use `horizontal` form type
* Avoid cropping of long form field labels
* Reintroduce "delete" action on table entities
* Fix placement of "reload" icon in table header

Tiny general form and table style improvements

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Util/TableUtil.tsx

This PR includes two bugfixes.
- Fixes handling of the 'create new entity' button
- Fixes sorting of numeric values in the EntityTable

Fixes resetting of the entity form & sorting of numeric values

---

src/Component/FormField/JSONEditor/JSONEditor.tsx
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx

This adds several enhancements to the handling of the dynamic form.

Form enhancements

---

.github/workflows/release.yaml

Integrates sonarscanner into builing pipeline

feat: integrates sonarscanner into builing pipeline

---

package-lock.json
package.json
src/Component/Dashboard/DashboardStatistics/DashboardStatistics.tsx
src/Component/EvictCache/EvictCache.tsx
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Component/GlobalSettings/GlobalSettingsRoot/GlobalSettingsRoot.tsx
src/Component/Header/Header.tsx
src/Component/LanguageSelector/index.less
src/Component/LanguageSelector/index.spec.tsx
src/Component/LanguageSelector/index.tsx
src/Component/LogSettings/LogLevelTable/LogLevelTable.tsx
src/Component/LogSettings/LogSettingsRoot/LogSettingsRoot.tsx
src/Component/Logs/Logs.tsx
src/Component/Menu/Navigation/Navigation.tsx
src/Component/Menu/User/User.tsx
src/Component/Metrics/MetricsRoot/MetricsRoot.tsx
src/Component/WelcomeDashboard/WelcomeDashboard.tsx
src/i18n/index.ts
src/i18n/translations.ts
src/index.tsx

Implements a i18next translation for the admin-client

feat: admin client translation

---

package-lock.json
package.json
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx
src/Component/Menu/User/User.tsx
src/Util/UserUtil.ts
src/i18n/translations.ts

Adds some usability improvements:
- translate table texts
- add loading indicators
- show gravatar

Usability improvements

---

.github/workflows/nodejs.yml
package-lock.json

- Updates package-lock.json so it's in sync with package.json. This will repair the automatic release
- switches to `npm ci` in the test pipeline. this ensures the package-lock.json will stay in sync (pull request where it's out of sync will fail)

fix: update package lock file and make sure it stays in sync

---

src/Component/Logs/Logs.tsx

Fix display area of status logs

---

package-lock.json
package.json
src/App.tsx
src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx
src/Component/GlobalSettings/GlobalSettingsRoot/GlobalSettingsRoot.tsx
src/Component/Header/Header.tsx
src/Component/ImageFile/ImageFileRoot/ImageFileRoot.tsx
src/Component/ImageFile/ImageFileTable/ImageFileTable.tsx
src/Component/LogSettings/LogSettingsRoot/LogSettingsRoot.tsx
src/Component/Logs/Logs.tsx
src/Component/Menu/Navigation/Navigation.tsx
src/Component/Metrics/MetricsRoot/MetricsRoot.tsx
src/Page/Portal/Portal.tsx

- new feature: adds keyboard shortcut `ctrl+s` to save entities
- fixes some translation issues
-  translate entityName in success message (8b577ddc42f00ae7be4bb90e612afb46528647ef)
- fixes an error where the success message was shown instead of the error message
- refactoring: upgrade to react-router-dom v6 (https://github.com/remix-run/react-router/blob/main/docs/upgrading/v5.md#upgrade-to-react-router-v6)

add keyboard shortcuts, react-router upgrade

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx

fix: adds a effect to update the table entries when the entity changes

---

src/Component/ImageFile/ImageFileRoot/ImageFileRoot.tsx
src/i18n/translations.ts

Adds missing translations for the ImageFileRoot.

feat: adds missing translation

---

.eslintrc.js
assets/formconfigs/application.json
package-lock.json
package.json
src/Component/FormField/UserPermissionGrid/PermissionSelect/PermissionSelect.spec.tsx
src/Component/FormField/UserPermissionGrid/PermissionSelect/PermissionSelect.tsx
src/Component/FormField/UserPermissionGrid/UserAvatar/UserAvatar.less
src/Component/FormField/UserPermissionGrid/UserAvatar/UserAvatar.spec.tsx
src/Component/FormField/UserPermissionGrid/UserAvatar/UserAvatar.tsx
src/Component/FormField/UserPermissionGrid/UserPermissionGrid.less
src/Component/FormField/UserPermissionGrid/UserPermissionGrid.spec.tsx
src/Component/FormField/UserPermissionGrid/UserPermissionGrid.tsx
src/Component/FormField/UserPermissionGrid/UserPermissionModal/UserPermissionModal.less
src/Component/FormField/UserPermissionGrid/UserPermissionModal/UserPermissionModal.spec.tsx
src/Component/FormField/UserPermissionGrid/UserPermissionModal/UserPermissionModal.tsx
src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx
src/Util/TranslationUtil.ts
src/i18n/translations.ts

This initializes the `UserPermissionGrid` that allows to manage the `UserInstancePermission`s for a given entity.
Requires [PR54](https://github.com/terrestris/shogun/pull/54) (shogun) and [PR96](https://github.com/terrestris/shogun-util/pull/96) (shogun-util).

Add `UserPermissionGrid`

---

src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx

The new delete message will be: ''The entity "{{entityName}}" was deleted''

fix: fixing typo

---

src/Component/FormField/UserPermissionGrid/UserAvatar/UserAvatar.tsx

Fixes a potential white screen error if the user mail is not set in the user provider.

Provide an empty string if no mail is present

---

src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx

Allows to configure pagination settings per entity. Uses pagination props from https://ant.design/components/pagination/

feat: allow pagination configuration per entity

---

assets/fallbackConfig.js
package-lock.json
src/Component/Menu/User/User.tsx

Fixes logging out without keycloak. Also hides the profile settings menu entry for non keycloak setups.
@terrestris/devs Please review.

fix: fix logout for non keycloak setups

---

src/custom.d.ts

This adds typing for the `shogunApplicationConfig`.

Adds typing for the shogun config

---

src/i18n/translations.ts

Changes the translation from "Upload Thema" to "Thema hochladen".

fix: upload button translation

---

package-lock.json
package.json
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/i18n/translations.ts
webpack.common.config.js

This fixes the upload of vector data by:
- providing the `attributes` of the upload layer candidate (this is required by the REST interface of GeoServer).
- setting the correct `nativeName` (= the name of the shapefile), it may differ from the name of the zip archive.

Fix layer upload

---

package-lock.json
package.json

This PR updates the shogun-util to version 5.4.1.

Updates sohgun-util to version 5.4.1

---

.github/workflows/nodejs.yml
.github/workflows/release.yaml
package-lock.json
package.json

This PR uses version 5.5.0 of shogun-util

Use next shogun-util version

---

README.md

This PR adds a linkt to the semantc-release FAQs

Updates readme and release shoguns layer editable function

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx

This also allows to upload files with the `application/x-zip-compressed` mimetype (will be determined for zip files in windows).

Add `application/x-zip-compressed` mimetype

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx

Follow up of #163.
Please note @terrestris/devs.

Also check for the extra mime type before uploading

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Util/TableUtil.tsx
src/i18n/translations.ts

Fixed a bug where switching entities, under certain circumstances like filtering, broke the listing and in some cases crashed the website. Additionally fixed a translation mistake in the search popup.

fix: fixed multiple bugs in GeneralEntityRoot and in the translation

---

assets/formconfigs/group.json
assets/formconfigs/user.json

See in title.
Please note @terrestris/devs.

Fix default user/group links to Keycloak

---

src/Component/Modal/ApplicationInfo/ApplicationInfo.less
src/Component/Modal/ApplicationInfo/ApplicationInfo.spec.tsx
src/Component/Modal/ApplicationInfo/ApplicationInfo.tsx
src/i18n/translations.ts

Changed the design and the text of Application info and added new translations for it.

feat: changed the design of applicationInfo.

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Util/TableUtil.tsx
src/i18n/translations.ts

This request fixes the following:
-Filtering not working when searching for something in GeneralEntityTable 
-In the filter field: undefined was appearing as a value to be searched. Now the sort field does what it is intended to do 
-Sorting not working properly
-paging not working properly
-changed a minor translation in the German translation for "Filter"

Fix: fixed bugs in paging, filtering and sorting

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx
src/Util/TableUtil.tsx

See title.
Fixes erroneous pagination for filtered tables.
BREAKING CHANGE: Remove pagination from TableConfig type

fix: disable pagination when table is filtered

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/Component/LayerPreview/LayerPreview.tsx

fix: pagination for filtered columns

---

src/Controller/GenericEntityController.ts

fix: resolve Promise on successful delete

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx

This change depends on following pull request: https://github.com/terrestris/shogun-docker/compare/application-default-configuration?expand=1

feat: adds a default configuration for application entity

---

src/Component/GeneralEntity/GeneralEntityTable/GeneralEntityTable.tsx

fix: initial sorting for name is now in alphabetic order

---

sonar-project.properties

fix: adds project version

---

.github/workflows/on-push-main.yml
sonar-project.properties

ci: make use of sonar-project-version

---

package-lock.json
package.json
src/Component/GeneralEntity/GeneralEntityForm/GeneralEntityForm.tsx
src/Controller/GenericEntityController.ts
src/custom.d.ts

This adds changes to the `GeneralEntityForm` and `GeneralEntityController` to allow the usage of public accesible entities.
It relies on https://github.com/terrestris/shogun/pull/850 and https://github.com/terrestris/shogun-util/pull/661.

Add handling for publicEntity

---

assets/index.html
src/App.less
src/App.tsx
src/Page/Portal/Portal.less
src/index.less
src/index.tsx

This updates some styling and renames the id and class of the react root to avoid confusion with the App component.
This also brings back the scrollbars at the right places.

Updates basic styling to bring back scrollbars

---

.github/workflows/on-push-main.yml
sonar-project.properties

This fixes the pipeline and adds the project version

Fix Sonarqube Pipeline

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.less
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx
src/i18n/translations.ts

redesigns warning modal to this:

chore: redesign warning modal so it is more convenient

---

src/App.less

before: (notice that the page is also scroll able)
after: 
(was tested for common monitor resolutions and adapts correctly when adjusted for width.)

Center shogun spinner

---

src/Component/ShogunSpinner/Shogun-spinner.spec.tsx

simple test that tests if the component can be rendered.

feat: adds a unittest for ShogunSpinner component

---

README.md

This adds workflow status badges to the README file.

docs: add workflow status to README

---

src/App.less

fix: hopefully centers loading icon

---

src/Component/FormField/Permission/GroupPermissionGrid/GroupPermissionGrid.tsx
src/Component/FormField/Permission/RolePermissionGrid/RolePermissionGrid.tsx

@terrestris/devs Please review.

Fix role and group permission grid

---

src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.less
src/Component/GeneralEntity/GeneralEntityRoot/GeneralEntityRoot.tsx

fix: removes non-functional review changes button

---

assets/fallbackConfig.js
src/Component/Menu/Navigation/Navigation.tsx
src/Page/Portal/Portal.tsx
src/custom.d.ts
src/i18n/translations.ts

fix: moves extenal links from the landing page to  admin

---

.releaserc.json

See in title.
Please note @terrestris/devs.

Add backport branch for v15

---

src/Component/FormField/JSONEditor/JSONEditor.less
src/Component/FullscreenWrapper/FullscreenWrapper.tsx

This aims to make the `FullscreenWrapper` more responsive.
Preview:

More responsive `FullscreenWrapper`

---

src/Component/CreateAllUsersButton/CreateAllUsersButton.tsx

fix: show error instead of success

---

src/Component/ImageFile/ImageFileForm/ImageFileForm.tsx

Set SHOGun base path in image url

---

src/Component/FormField/MarkdownEditor/MarkdownEditor.less

Ensure the markdown editor gets the full height of the parent

---

src/App.tsx

Load all layers for the `layerId` suggestion list
